//<auto-generated/>
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace QuickForm.Modules.Survey.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class FormStatus : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "IsClosed",
                schema: "Survey",
                table: "Forms");

            migrationBuilder.DropColumn(
                name: "IsPublished",
                schema: "Survey",
                table: "Forms");

            migrationBuilder.AlterColumn<string>(
                name: "Description",
                schema: "Survey",
                table: "Forms",
                type: "nvarchar(255)",
                maxLength: 255,
                nullable: false,
                oldClrType: typeof(string),
                oldType: "nvarchar(500)",
                oldMaxLength: 500);

            migrationBuilder.AddColumn<Guid>(
                name: "IdStatus",
                schema: "Survey",
                table: "Forms",
                type: "uniqueidentifier",
                nullable: false,
                defaultValue: new Guid("00000000-0000-0000-0000-000000000000"));

            migrationBuilder.CreateTable(
                name: "FormAction",
                schema: "Survey",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    CreatedBy = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: false),
                    CreatedDate = table.Column<DateTime>(type: "datetime2", nullable: false),
                    ModifiedBy = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true),
                    ModifiedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    IsDeleted = table.Column<bool>(type: "bit", nullable: false, defaultValue: false),
                    DeletedAt = table.Column<DateTime>(type: "datetime2", nullable: true),
                    DeletedBy = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true),
                    KeyName = table.Column<string>(type: "nvarchar(200)", maxLength: 200, nullable: false),
                    Description = table.Column<string>(type: "nvarchar(1000)", maxLength: 1000, nullable: true),
                    SortOrder = table.Column<int>(type: "int", nullable: false, defaultValue: 0)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_FormAction", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "FormStatus",
                schema: "Survey",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    CreatedBy = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: false),
                    CreatedDate = table.Column<DateTime>(type: "datetime2", nullable: false),
                    ModifiedBy = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true),
                    ModifiedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    IsDeleted = table.Column<bool>(type: "bit", nullable: false, defaultValue: false),
                    DeletedAt = table.Column<DateTime>(type: "datetime2", nullable: true),
                    DeletedBy = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true),
                    KeyName = table.Column<string>(type: "nvarchar(200)", maxLength: 200, nullable: false),
                    Description = table.Column<string>(type: "nvarchar(1000)", maxLength: 1000, nullable: true),
                    SortOrder = table.Column<int>(type: "int", nullable: false, defaultValue: 0),
                    Color = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: false),
                    Icon = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_FormStatus", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "FormStatusPermission",
                schema: "Survey",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    IdFormAction = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    IdFormStatus = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    CreatedBy = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: false),
                    CreatedDate = table.Column<DateTime>(type: "datetime2", nullable: false),
                    ModifiedBy = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true),
                    ModifiedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    IsDeleted = table.Column<bool>(type: "bit", nullable: false, defaultValue: false),
                    DeletedAt = table.Column<DateTime>(type: "datetime2", nullable: true),
                    DeletedBy = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_FormStatusPermission", x => x.Id);
                    table.ForeignKey(
                        name: "FK_FormStatusPermission_FormAction_IdFormAction",
                        column: x => x.IdFormAction,
                        principalSchema: "Survey",
                        principalTable: "FormAction",
                        principalColumn: "Id");
                    table.ForeignKey(
                        name: "FK_FormStatusPermission_FormStatus_IdFormStatus",
                        column: x => x.IdFormStatus,
                        principalSchema: "Survey",
                        principalTable: "FormStatus",
                        principalColumn: "Id");
                });

            migrationBuilder.CreateIndex(
                name: "IX_Forms_IdStatus",
                schema: "Survey",
                table: "Forms",
                column: "IdStatus");

            migrationBuilder.CreateIndex(
                name: "IX_FormActionDomain_IsDeleted",
                schema: "Survey",
                table: "FormAction",
                column: "IsDeleted");

            migrationBuilder.CreateIndex(
                name: "IX_FormActionDomain_KeyName",
                schema: "Survey",
                table: "FormAction",
                column: "KeyName");

            migrationBuilder.CreateIndex(
                name: "IX_FormStatusDomain_IsDeleted",
                schema: "Survey",
                table: "FormStatus",
                column: "IsDeleted");

            migrationBuilder.CreateIndex(
                name: "IX_FormStatusDomain_KeyName",
                schema: "Survey",
                table: "FormStatus",
                column: "KeyName");

            migrationBuilder.CreateIndex(
                name: "IX_FormStatusPermission_IdFormAction",
                schema: "Survey",
                table: "FormStatusPermission",
                column: "IdFormAction");

            migrationBuilder.CreateIndex(
                name: "IX_FormStatusPermission_IdFormStatus",
                schema: "Survey",
                table: "FormStatusPermission",
                column: "IdFormStatus");

            migrationBuilder.CreateIndex(
                name: "IX_FormStatusPermissionDomain_IsDeleted",
                schema: "Survey",
                table: "FormStatusPermission",
                column: "IsDeleted");

            migrationBuilder.AddForeignKey(
                name: "FK_Forms_FormStatus_IdStatus",
                schema: "Survey",
                table: "Forms",
                column: "IdStatus",
                principalSchema: "Survey",
                principalTable: "FormStatus",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Forms_FormStatus_IdStatus",
                schema: "Survey",
                table: "Forms");

            migrationBuilder.DropTable(
                name: "FormStatusPermission",
                schema: "Survey");

            migrationBuilder.DropTable(
                name: "FormAction",
                schema: "Survey");

            migrationBuilder.DropTable(
                name: "FormStatus",
                schema: "Survey");

            migrationBuilder.DropIndex(
                name: "IX_Forms_IdStatus",
                schema: "Survey",
                table: "Forms");

            migrationBuilder.DropColumn(
                name: "IdStatus",
                schema: "Survey",
                table: "Forms");

            migrationBuilder.AlterColumn<string>(
                name: "Description",
                schema: "Survey",
                table: "Forms",
                type: "nvarchar(500)",
                maxLength: 500,
                nullable: false,
                oldClrType: typeof(string),
                oldType: "nvarchar(255)",
                oldMaxLength: 255);

            migrationBuilder.AddColumn<bool>(
                name: "IsClosed",
                schema: "Survey",
                table: "Forms",
                type: "bit",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<bool>(
                name: "IsPublished",
                schema: "Survey",
                table: "Forms",
                type: "bit",
                nullable: false,
                defaultValue: false);
        }
    }
}
