//<auto-generated/>
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace QuickForm.Modules.Survey.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class AddEntitiesQuestionTypeAndQuestionTypeAttribute : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<Guid>(
                name: "customerId",
                schema: "Survey",
                table: "Forms",
                type: "uniqueidentifier",
                nullable: true);

            migrationBuilder.CreateTable(
                name: "QuestionType",
                schema: "Survey",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    KeyName = table.Column<string>(type: "nvarchar(255)", maxLength: 255, nullable: false),
                    CreatedBy = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: false),
                    ModifiedBy = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true),
                    CreatedDate = table.Column<DateTime>(type: "datetime2", nullable: false),
                    ModifiedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    IsActive = table.Column<bool>(type: "bit", nullable: false, defaultValue: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_QuestionType", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "QuestionTypeAttribute",
                schema: "Survey",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    IdQuestionType = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    IdAttribute = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    IsRequired = table.Column<bool>(type: "bit", nullable: false),
                    CreatedBy = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: false),
                    ModifiedBy = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true),
                    CreatedDate = table.Column<DateTime>(type: "datetime2", nullable: false),
                    ModifiedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    IsActive = table.Column<bool>(type: "bit", nullable: false, defaultValue: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_QuestionTypeAttribute", x => x.Id);
                    table.ForeignKey(
                        name: "FK_QuestionTypeAttribute_Attribute_IdAttribute",
                        column: x => x.IdAttribute,
                        principalSchema: "Survey",
                        principalTable: "Attribute",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_QuestionTypeAttribute_QuestionType_IdQuestionType",
                        column: x => x.IdQuestionType,
                        principalSchema: "Survey",
                        principalTable: "QuestionType",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_Forms_customerId",
                schema: "Survey",
                table: "Forms",
                column: "customerId");

            migrationBuilder.CreateIndex(
                name: "IX_QuestionType_KeyName",
                schema: "Survey",
                table: "QuestionType",
                column: "KeyName",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_QuestionTypeDomain_IsActive",
                schema: "Survey",
                table: "QuestionType",
                column: "IsActive");

            migrationBuilder.CreateIndex(
                name: "IX_QuestionTypeAttribute_IdAttribute",
                schema: "Survey",
                table: "QuestionTypeAttribute",
                column: "IdAttribute");

            migrationBuilder.CreateIndex(
                name: "IX_QuestionTypeAttribute_IdQuestionType",
                schema: "Survey",
                table: "QuestionTypeAttribute",
                column: "IdQuestionType");

            migrationBuilder.CreateIndex(
                name: "IX_QuestionTypeAttributeDomain_IsActive",
                schema: "Survey",
                table: "QuestionTypeAttribute",
                column: "IsActive");

            migrationBuilder.AddForeignKey(
                name: "FK_Forms_Customers_customerId",
                schema: "Survey",
                table: "Forms",
                column: "customerId",
                principalSchema: "Survey",
                principalTable: "Customers",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Forms_Customers_customerId",
                schema: "Survey",
                table: "Forms");

            migrationBuilder.DropTable(
                name: "QuestionTypeAttribute",
                schema: "Survey");

            migrationBuilder.DropTable(
                name: "QuestionType",
                schema: "Survey");

            migrationBuilder.DropIndex(
                name: "IX_Forms_customerId",
                schema: "Survey",
                table: "Forms");

            migrationBuilder.DropColumn(
                name: "customerId",
                schema: "Survey",
                table: "Forms");
        }
    }
}
