//<auto-generated/>
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace QuickForm.Modules.Survey.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class SetCambiosEnAuditoria : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "IX_QuestionTypeAttributeDomain_IsActive",
                schema: "Survey",
                table: "QuestionTypeAttribute");

            migrationBuilder.DropIndex(
                name: "IX_QuestionTypeDomain_IsActive",
                schema: "Survey",
                table: "QuestionType");

            migrationBuilder.DropIndex(
                name: "IX_QuestionAttributeValueDomain_IsActive",
                schema: "Survey",
                table: "QuestionAttributeValue");

            migrationBuilder.DropIndex(
                name: "IX_QuestionDomain_IsActive",
                schema: "Survey",
                table: "Question");

            migrationBuilder.DropIndex(
                name: "IX_FormSectionDomain_IsActive",
                schema: "Survey",
                table: "FormSection");

            migrationBuilder.DropIndex(
                name: "IX_FormDomain_IsActive",
                schema: "Survey",
                table: "Forms");

            migrationBuilder.DropIndex(
                name: "IX_DataTypeDomain_IsActive",
                schema: "Survey",
                table: "DataType");

            migrationBuilder.DropIndex(
                name: "IX_Customer_IsActive",
                schema: "Survey",
                table: "Customers");

            migrationBuilder.DropIndex(
                name: "IX_AttributeDomain_IsActive",
                schema: "Survey",
                table: "Attribute");

            migrationBuilder.DropColumn(
                name: "IsActive",
                schema: "Survey",
                table: "QuestionTypeAttribute");

            migrationBuilder.DropColumn(
                name: "IsActive",
                schema: "Survey",
                table: "QuestionType");

            migrationBuilder.DropColumn(
                name: "IsActive",
                schema: "Survey",
                table: "QuestionAttributeValue");

            migrationBuilder.DropColumn(
                name: "IsActive",
                schema: "Survey",
                table: "Question");

            migrationBuilder.DropColumn(
                name: "IsActive",
                schema: "Survey",
                table: "FormSection");

            migrationBuilder.DropColumn(
                name: "IsActive",
                schema: "Survey",
                table: "Forms");

            migrationBuilder.DropColumn(
                name: "IsActive",
                schema: "Survey",
                table: "DataType");

            migrationBuilder.DropColumn(
                name: "IsActive",
                schema: "Survey",
                table: "Customers");

            migrationBuilder.DropColumn(
                name: "IsActive",
                schema: "Survey",
                table: "Attribute");

            migrationBuilder.RenameColumn(
                name: "TypeName",
                schema: "Survey",
                table: "Audit",
                newName: "ActionName");

            migrationBuilder.RenameColumn(
                name: "Type",
                schema: "Survey",
                table: "Audit",
                newName: "Action");

            migrationBuilder.AddColumn<DateTime>(
                name: "DeletedAt",
                schema: "Survey",
                table: "QuestionTypeAttribute",
                type: "datetime2",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "DeletedBy",
                schema: "Survey",
                table: "QuestionTypeAttribute",
                type: "nvarchar(100)",
                maxLength: 100,
                nullable: true);

            migrationBuilder.AddColumn<bool>(
                name: "IsDeleted",
                schema: "Survey",
                table: "QuestionTypeAttribute",
                type: "bit",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<DateTime>(
                name: "DeletedAt",
                schema: "Survey",
                table: "QuestionType",
                type: "datetime2",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "DeletedBy",
                schema: "Survey",
                table: "QuestionType",
                type: "nvarchar(100)",
                maxLength: 100,
                nullable: true);

            migrationBuilder.AddColumn<bool>(
                name: "IsDeleted",
                schema: "Survey",
                table: "QuestionType",
                type: "bit",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<DateTime>(
                name: "DeletedAt",
                schema: "Survey",
                table: "QuestionAttributeValue",
                type: "datetime2",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "DeletedBy",
                schema: "Survey",
                table: "QuestionAttributeValue",
                type: "nvarchar(100)",
                maxLength: 100,
                nullable: true);

            migrationBuilder.AddColumn<bool>(
                name: "IsDeleted",
                schema: "Survey",
                table: "QuestionAttributeValue",
                type: "bit",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<DateTime>(
                name: "DeletedAt",
                schema: "Survey",
                table: "Question",
                type: "datetime2",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "DeletedBy",
                schema: "Survey",
                table: "Question",
                type: "nvarchar(100)",
                maxLength: 100,
                nullable: true);

            migrationBuilder.AddColumn<bool>(
                name: "IsDeleted",
                schema: "Survey",
                table: "Question",
                type: "bit",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<DateTime>(
                name: "DeletedAt",
                schema: "Survey",
                table: "FormSection",
                type: "datetime2",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "DeletedBy",
                schema: "Survey",
                table: "FormSection",
                type: "nvarchar(100)",
                maxLength: 100,
                nullable: true);

            migrationBuilder.AddColumn<bool>(
                name: "IsDeleted",
                schema: "Survey",
                table: "FormSection",
                type: "bit",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<DateTime>(
                name: "DeletedAt",
                schema: "Survey",
                table: "Forms",
                type: "datetime2",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "DeletedBy",
                schema: "Survey",
                table: "Forms",
                type: "nvarchar(100)",
                maxLength: 100,
                nullable: true);

            migrationBuilder.AddColumn<bool>(
                name: "IsDeleted",
                schema: "Survey",
                table: "Forms",
                type: "bit",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<DateTime>(
                name: "DeletedAt",
                schema: "Survey",
                table: "DataType",
                type: "datetime2",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "DeletedBy",
                schema: "Survey",
                table: "DataType",
                type: "nvarchar(100)",
                maxLength: 100,
                nullable: true);

            migrationBuilder.AddColumn<bool>(
                name: "IsDeleted",
                schema: "Survey",
                table: "DataType",
                type: "bit",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<DateTime>(
                name: "DeletedAt",
                schema: "Survey",
                table: "Customers",
                type: "datetime2",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "DeletedBy",
                schema: "Survey",
                table: "Customers",
                type: "nvarchar(100)",
                maxLength: 100,
                nullable: true);

            migrationBuilder.AddColumn<bool>(
                name: "IsDeleted",
                schema: "Survey",
                table: "Customers",
                type: "bit",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<DateTime>(
                name: "DeletedAt",
                schema: "Survey",
                table: "Attribute",
                type: "datetime2",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "DeletedBy",
                schema: "Survey",
                table: "Attribute",
                type: "nvarchar(100)",
                maxLength: 100,
                nullable: true);

            migrationBuilder.AddColumn<bool>(
                name: "IsDeleted",
                schema: "Survey",
                table: "Attribute",
                type: "bit",
                nullable: false,
                defaultValue: false);

            migrationBuilder.CreateIndex(
                name: "IX_QuestionTypeAttributeDomain_IsDeleted",
                schema: "Survey",
                table: "QuestionTypeAttribute",
                column: "IsDeleted");

            migrationBuilder.CreateIndex(
                name: "IX_QuestionTypeDomain_IsDeleted",
                schema: "Survey",
                table: "QuestionType",
                column: "IsDeleted");

            migrationBuilder.CreateIndex(
                name: "IX_QuestionAttributeValueDomain_IsDeleted",
                schema: "Survey",
                table: "QuestionAttributeValue",
                column: "IsDeleted");

            migrationBuilder.CreateIndex(
                name: "IX_QuestionDomain_IsDeleted",
                schema: "Survey",
                table: "Question",
                column: "IsDeleted");

            migrationBuilder.CreateIndex(
                name: "IX_FormSectionDomain_IsDeleted",
                schema: "Survey",
                table: "FormSection",
                column: "IsDeleted");

            migrationBuilder.CreateIndex(
                name: "IX_FormDomain_IsDeleted",
                schema: "Survey",
                table: "Forms",
                column: "IsDeleted");

            migrationBuilder.CreateIndex(
                name: "IX_DataTypeDomain_IsDeleted",
                schema: "Survey",
                table: "DataType",
                column: "IsDeleted");

            migrationBuilder.CreateIndex(
                name: "IX_Customer_IsDeleted",
                schema: "Survey",
                table: "Customers",
                column: "IsDeleted");

            migrationBuilder.CreateIndex(
                name: "IX_AttributeDomain_IsDeleted",
                schema: "Survey",
                table: "Attribute",
                column: "IsDeleted");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "IX_QuestionTypeAttributeDomain_IsDeleted",
                schema: "Survey",
                table: "QuestionTypeAttribute");

            migrationBuilder.DropIndex(
                name: "IX_QuestionTypeDomain_IsDeleted",
                schema: "Survey",
                table: "QuestionType");

            migrationBuilder.DropIndex(
                name: "IX_QuestionAttributeValueDomain_IsDeleted",
                schema: "Survey",
                table: "QuestionAttributeValue");

            migrationBuilder.DropIndex(
                name: "IX_QuestionDomain_IsDeleted",
                schema: "Survey",
                table: "Question");

            migrationBuilder.DropIndex(
                name: "IX_FormSectionDomain_IsDeleted",
                schema: "Survey",
                table: "FormSection");

            migrationBuilder.DropIndex(
                name: "IX_FormDomain_IsDeleted",
                schema: "Survey",
                table: "Forms");

            migrationBuilder.DropIndex(
                name: "IX_DataTypeDomain_IsDeleted",
                schema: "Survey",
                table: "DataType");

            migrationBuilder.DropIndex(
                name: "IX_Customer_IsDeleted",
                schema: "Survey",
                table: "Customers");

            migrationBuilder.DropIndex(
                name: "IX_AttributeDomain_IsDeleted",
                schema: "Survey",
                table: "Attribute");

            migrationBuilder.DropColumn(
                name: "DeletedAt",
                schema: "Survey",
                table: "QuestionTypeAttribute");

            migrationBuilder.DropColumn(
                name: "DeletedBy",
                schema: "Survey",
                table: "QuestionTypeAttribute");

            migrationBuilder.DropColumn(
                name: "IsDeleted",
                schema: "Survey",
                table: "QuestionTypeAttribute");

            migrationBuilder.DropColumn(
                name: "DeletedAt",
                schema: "Survey",
                table: "QuestionType");

            migrationBuilder.DropColumn(
                name: "DeletedBy",
                schema: "Survey",
                table: "QuestionType");

            migrationBuilder.DropColumn(
                name: "IsDeleted",
                schema: "Survey",
                table: "QuestionType");

            migrationBuilder.DropColumn(
                name: "DeletedAt",
                schema: "Survey",
                table: "QuestionAttributeValue");

            migrationBuilder.DropColumn(
                name: "DeletedBy",
                schema: "Survey",
                table: "QuestionAttributeValue");

            migrationBuilder.DropColumn(
                name: "IsDeleted",
                schema: "Survey",
                table: "QuestionAttributeValue");

            migrationBuilder.DropColumn(
                name: "DeletedAt",
                schema: "Survey",
                table: "Question");

            migrationBuilder.DropColumn(
                name: "DeletedBy",
                schema: "Survey",
                table: "Question");

            migrationBuilder.DropColumn(
                name: "IsDeleted",
                schema: "Survey",
                table: "Question");

            migrationBuilder.DropColumn(
                name: "DeletedAt",
                schema: "Survey",
                table: "FormSection");

            migrationBuilder.DropColumn(
                name: "DeletedBy",
                schema: "Survey",
                table: "FormSection");

            migrationBuilder.DropColumn(
                name: "IsDeleted",
                schema: "Survey",
                table: "FormSection");

            migrationBuilder.DropColumn(
                name: "DeletedAt",
                schema: "Survey",
                table: "Forms");

            migrationBuilder.DropColumn(
                name: "DeletedBy",
                schema: "Survey",
                table: "Forms");

            migrationBuilder.DropColumn(
                name: "IsDeleted",
                schema: "Survey",
                table: "Forms");

            migrationBuilder.DropColumn(
                name: "DeletedAt",
                schema: "Survey",
                table: "DataType");

            migrationBuilder.DropColumn(
                name: "DeletedBy",
                schema: "Survey",
                table: "DataType");

            migrationBuilder.DropColumn(
                name: "IsDeleted",
                schema: "Survey",
                table: "DataType");

            migrationBuilder.DropColumn(
                name: "DeletedAt",
                schema: "Survey",
                table: "Customers");

            migrationBuilder.DropColumn(
                name: "DeletedBy",
                schema: "Survey",
                table: "Customers");

            migrationBuilder.DropColumn(
                name: "IsDeleted",
                schema: "Survey",
                table: "Customers");

            migrationBuilder.DropColumn(
                name: "DeletedAt",
                schema: "Survey",
                table: "Attribute");

            migrationBuilder.DropColumn(
                name: "DeletedBy",
                schema: "Survey",
                table: "Attribute");

            migrationBuilder.DropColumn(
                name: "IsDeleted",
                schema: "Survey",
                table: "Attribute");

            migrationBuilder.RenameColumn(
                name: "ActionName",
                schema: "Survey",
                table: "Audit",
                newName: "TypeName");

            migrationBuilder.RenameColumn(
                name: "Action",
                schema: "Survey",
                table: "Audit",
                newName: "Type");

            migrationBuilder.AddColumn<bool>(
                name: "IsActive",
                schema: "Survey",
                table: "QuestionTypeAttribute",
                type: "bit",
                nullable: false,
                defaultValue: true);

            migrationBuilder.AddColumn<bool>(
                name: "IsActive",
                schema: "Survey",
                table: "QuestionType",
                type: "bit",
                nullable: false,
                defaultValue: true);

            migrationBuilder.AddColumn<bool>(
                name: "IsActive",
                schema: "Survey",
                table: "QuestionAttributeValue",
                type: "bit",
                nullable: false,
                defaultValue: true);

            migrationBuilder.AddColumn<bool>(
                name: "IsActive",
                schema: "Survey",
                table: "Question",
                type: "bit",
                nullable: false,
                defaultValue: true);

            migrationBuilder.AddColumn<bool>(
                name: "IsActive",
                schema: "Survey",
                table: "FormSection",
                type: "bit",
                nullable: false,
                defaultValue: true);

            migrationBuilder.AddColumn<bool>(
                name: "IsActive",
                schema: "Survey",
                table: "Forms",
                type: "bit",
                nullable: false,
                defaultValue: true);

            migrationBuilder.AddColumn<bool>(
                name: "IsActive",
                schema: "Survey",
                table: "DataType",
                type: "bit",
                nullable: false,
                defaultValue: true);

            migrationBuilder.AddColumn<bool>(
                name: "IsActive",
                schema: "Survey",
                table: "Customers",
                type: "bit",
                nullable: false,
                defaultValue: true);

            migrationBuilder.AddColumn<bool>(
                name: "IsActive",
                schema: "Survey",
                table: "Attribute",
                type: "bit",
                nullable: false,
                defaultValue: true);

            migrationBuilder.CreateIndex(
                name: "IX_QuestionTypeAttributeDomain_IsActive",
                schema: "Survey",
                table: "QuestionTypeAttribute",
                column: "IsActive");

            migrationBuilder.CreateIndex(
                name: "IX_QuestionTypeDomain_IsActive",
                schema: "Survey",
                table: "QuestionType",
                column: "IsActive");

            migrationBuilder.CreateIndex(
                name: "IX_QuestionAttributeValueDomain_IsActive",
                schema: "Survey",
                table: "QuestionAttributeValue",
                column: "IsActive");

            migrationBuilder.CreateIndex(
                name: "IX_QuestionDomain_IsActive",
                schema: "Survey",
                table: "Question",
                column: "IsActive");

            migrationBuilder.CreateIndex(
                name: "IX_FormSectionDomain_IsActive",
                schema: "Survey",
                table: "FormSection",
                column: "IsActive");

            migrationBuilder.CreateIndex(
                name: "IX_FormDomain_IsActive",
                schema: "Survey",
                table: "Forms",
                column: "IsActive");

            migrationBuilder.CreateIndex(
                name: "IX_DataTypeDomain_IsActive",
                schema: "Survey",
                table: "DataType",
                column: "IsActive");

            migrationBuilder.CreateIndex(
                name: "IX_Customer_IsActive",
                schema: "Survey",
                table: "Customers",
                column: "IsActive");

            migrationBuilder.CreateIndex(
                name: "IX_AttributeDomain_IsActive",
                schema: "Survey",
                table: "Attribute",
                column: "IsActive");
        }
    }
}
