//<auto-generated/>
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace QuickForm.Modules.Survey.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class FormSection : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Question_Forms_IdForm",
                schema: "Survey",
                table: "Question");

            migrationBuilder.RenameColumn(
                name: "Order",
                schema: "Survey",
                table: "Question",
                newName: "SortOrder");

            migrationBuilder.RenameColumn(
                name: "IdForm",
                schema: "Survey",
                table: "Question",
                newName: "IdFormSection");

            migrationBuilder.RenameIndex(
                name: "IX_Question_IdForm",
                schema: "Survey",
                table: "Question",
                newName: "IX_Question_IdFormSection");

            migrationBuilder.CreateTable(
                name: "FormSection",
                schema: "Survey",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    IdForm = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    Description = table.Column<string>(type: "nvarchar(500)", maxLength: 500, nullable: false),
                    Title = table.Column<string>(type: "nvarchar(255)", maxLength: 255, nullable: false),
                    SortOrder = table.Column<int>(type: "int", nullable: false),
                    CreatedBy = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: false),
                    ModifiedBy = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true),
                    CreatedDate = table.Column<DateTime>(type: "datetime2", nullable: false),
                    ModifiedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    IsActive = table.Column<bool>(type: "bit", nullable: false, defaultValue: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_FormSection", x => x.Id);
                    table.ForeignKey(
                        name: "FK_FormSection_Forms_IdForm",
                        column: x => x.IdForm,
                        principalSchema: "Survey",
                        principalTable: "Forms",
                        principalColumn: "Id");
                });

            migrationBuilder.CreateIndex(
                name: "IX_FormSection_IdForm",
                schema: "Survey",
                table: "FormSection",
                column: "IdForm");

            migrationBuilder.CreateIndex(
                name: "IX_FormSectionDomain_IsActive",
                schema: "Survey",
                table: "FormSection",
                column: "IsActive");

            migrationBuilder.AddForeignKey(
                name: "FK_Question_FormSection_IdFormSection",
                schema: "Survey",
                table: "Question",
                column: "IdFormSection",
                principalSchema: "Survey",
                principalTable: "FormSection",
                principalColumn: "Id");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Question_FormSection_IdFormSection",
                schema: "Survey",
                table: "Question");

            migrationBuilder.DropTable(
                name: "FormSection",
                schema: "Survey");

            migrationBuilder.RenameColumn(
                name: "SortOrder",
                schema: "Survey",
                table: "Question",
                newName: "Order");

            migrationBuilder.RenameColumn(
                name: "IdFormSection",
                schema: "Survey",
                table: "Question",
                newName: "IdForm");

            migrationBuilder.RenameIndex(
                name: "IX_Question_IdFormSection",
                schema: "Survey",
                table: "Question",
                newName: "IX_Question_IdForm");

            migrationBuilder.AddForeignKey(
                name: "FK_Question_Forms_IdForm",
                schema: "Survey",
                table: "Question",
                column: "IdForm",
                principalSchema: "Survey",
                principalTable: "Forms",
                principalColumn: "Id");
        }
    }
}
