//<auto-generated/>
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace QuickForm.Modules.Survey.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class ChangeFieldCustomerIdPorIdCustomer : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Forms_Customers_customerId",
                schema: "Survey",
                table: "Forms");

            migrationBuilder.RenameColumn(
                name: "customerId",
                schema: "Survey",
                table: "Forms",
                newName: "IdCustomer");

            migrationBuilder.RenameIndex(
                name: "IX_Forms_customerId",
                schema: "Survey",
                table: "Forms",
                newName: "IX_Forms_IdCustomer");

            migrationBuilder.AddForeignKey(
                name: "FK_Forms_Customers_IdCustomer",
                schema: "Survey",
                table: "Forms",
                column: "IdCustomer",
                principalSchema: "Survey",
                principalTable: "Customers",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Forms_Customers_IdCustomer",
                schema: "Survey",
                table: "Forms");

            migrationBuilder.RenameColumn(
                name: "IdCustomer",
                schema: "Survey",
                table: "Forms",
                newName: "customerId");

            migrationBuilder.RenameIndex(
                name: "IX_Forms_IdCustomer",
                schema: "Survey",
                table: "Forms",
                newName: "IX_Forms_customerId");

            migrationBuilder.AddForeignKey(
                name: "FK_Forms_Customers_customerId",
                schema: "Survey",
                table: "Forms",
                column: "customerId",
                principalSchema: "Survey",
                principalTable: "Customers",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);
        }
    }
}
