//<auto-generated/>
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace QuickForm.Modules.Survey.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class RuleQuestion : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "IX_Attribute_KeyName",
                schema: "Survey",
                table: "Attribute");

            migrationBuilder.AlterColumn<string>(
                name: "KeyName",
                schema: "Survey",
                table: "Attribute",
                type: "nvarchar(200)",
                maxLength: 200,
                nullable: false,
                oldClrType: typeof(string),
                oldType: "nvarchar(255)",
                oldMaxLength: 255);

            migrationBuilder.AlterColumn<string>(
                name: "Description",
                schema: "Survey",
                table: "Attribute",
                type: "nvarchar(1000)",
                maxLength: 1000,
                nullable: true,
                oldClrType: typeof(string),
                oldType: "nvarchar(255)",
                oldMaxLength: 255);

            migrationBuilder.AddColumn<int>(
                name: "SortOrder",
                schema: "Survey",
                table: "Attribute",
                type: "int",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.CreateTable(
                name: "Rule",
                schema: "Survey",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    IdDataType = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    CreatedBy = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: false),
                    CreatedDate = table.Column<DateTime>(type: "datetime2", nullable: false),
                    ModifiedBy = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true),
                    ModifiedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    IsDeleted = table.Column<bool>(type: "bit", nullable: false, defaultValue: false),
                    DeletedAt = table.Column<DateTime>(type: "datetime2", nullable: true),
                    DeletedBy = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true),
                    KeyName = table.Column<string>(type: "nvarchar(200)", maxLength: 200, nullable: false),
                    Description = table.Column<string>(type: "nvarchar(1000)", maxLength: 1000, nullable: true),
                    SortOrder = table.Column<int>(type: "int", nullable: false, defaultValue: 0)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Rule", x => x.Id);
                    table.ForeignKey(
                        name: "FK_Rule_DataType_IdDataType",
                        column: x => x.IdDataType,
                        principalSchema: "Survey",
                        principalTable: "DataType",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "QuestionTypeRule",
                schema: "Survey",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    IdQuestionType = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    IdRule = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    IsRequired = table.Column<bool>(type: "bit", nullable: false),
                    CreatedBy = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: false),
                    CreatedDate = table.Column<DateTime>(type: "datetime2", nullable: false),
                    ModifiedBy = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true),
                    ModifiedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    IsDeleted = table.Column<bool>(type: "bit", nullable: false, defaultValue: false),
                    DeletedAt = table.Column<DateTime>(type: "datetime2", nullable: true),
                    DeletedBy = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_QuestionTypeRule", x => x.Id);
                    table.ForeignKey(
                        name: "FK_QuestionTypeRule_QuestionType_IdQuestionType",
                        column: x => x.IdQuestionType,
                        principalSchema: "Survey",
                        principalTable: "QuestionType",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_QuestionTypeRule_Rule_IdRule",
                        column: x => x.IdRule,
                        principalSchema: "Survey",
                        principalTable: "Rule",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "QuestionRuleValue",
                schema: "Survey",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    IdQuestion = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    IdQuestionTypeRule = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    Value = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CreatedBy = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: false),
                    CreatedDate = table.Column<DateTime>(type: "datetime2", nullable: false),
                    ModifiedBy = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true),
                    ModifiedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    IsDeleted = table.Column<bool>(type: "bit", nullable: false, defaultValue: false),
                    DeletedAt = table.Column<DateTime>(type: "datetime2", nullable: true),
                    DeletedBy = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_QuestionRuleValue", x => x.Id);
                    table.ForeignKey(
                        name: "FK_QuestionRuleValue_QuestionTypeRule_IdQuestionTypeRule",
                        column: x => x.IdQuestionTypeRule,
                        principalSchema: "Survey",
                        principalTable: "QuestionTypeRule",
                        principalColumn: "Id");
                    table.ForeignKey(
                        name: "FK_QuestionRuleValue_Question_IdQuestion",
                        column: x => x.IdQuestion,
                        principalSchema: "Survey",
                        principalTable: "Question",
                        principalColumn: "Id");
                });

            migrationBuilder.CreateIndex(
                name: "IX_AttributeDomain_KeyName",
                schema: "Survey",
                table: "Attribute",
                column: "KeyName");

            migrationBuilder.CreateIndex(
                name: "IX_QuestionRuleValue_IdQuestion",
                schema: "Survey",
                table: "QuestionRuleValue",
                column: "IdQuestion");

            migrationBuilder.CreateIndex(
                name: "IX_QuestionRuleValue_IdQuestionTypeRule",
                schema: "Survey",
                table: "QuestionRuleValue",
                column: "IdQuestionTypeRule");

            migrationBuilder.CreateIndex(
                name: "IX_QuestionRuleValueDomain_IsDeleted",
                schema: "Survey",
                table: "QuestionRuleValue",
                column: "IsDeleted");

            migrationBuilder.CreateIndex(
                name: "IX_QuestionTypeRule_IdQuestionType",
                schema: "Survey",
                table: "QuestionTypeRule",
                column: "IdQuestionType");

            migrationBuilder.CreateIndex(
                name: "IX_QuestionTypeRule_IdRule",
                schema: "Survey",
                table: "QuestionTypeRule",
                column: "IdRule");

            migrationBuilder.CreateIndex(
                name: "IX_QuestionTypeRuleDomain_IsDeleted",
                schema: "Survey",
                table: "QuestionTypeRule",
                column: "IsDeleted");

            migrationBuilder.CreateIndex(
                name: "IX_Rule_IdDataType",
                schema: "Survey",
                table: "Rule",
                column: "IdDataType");

            migrationBuilder.CreateIndex(
                name: "IX_RuleDomain_IsDeleted",
                schema: "Survey",
                table: "Rule",
                column: "IsDeleted");

            migrationBuilder.CreateIndex(
                name: "IX_RuleDomain_KeyName",
                schema: "Survey",
                table: "Rule",
                column: "KeyName");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "QuestionRuleValue",
                schema: "Survey");

            migrationBuilder.DropTable(
                name: "QuestionTypeRule",
                schema: "Survey");

            migrationBuilder.DropTable(
                name: "Rule",
                schema: "Survey");

            migrationBuilder.DropIndex(
                name: "IX_AttributeDomain_KeyName",
                schema: "Survey",
                table: "Attribute");

            migrationBuilder.DropColumn(
                name: "SortOrder",
                schema: "Survey",
                table: "Attribute");

            migrationBuilder.AlterColumn<string>(
                name: "KeyName",
                schema: "Survey",
                table: "Attribute",
                type: "nvarchar(255)",
                maxLength: 255,
                nullable: false,
                oldClrType: typeof(string),
                oldType: "nvarchar(200)",
                oldMaxLength: 200);

            migrationBuilder.AlterColumn<string>(
                name: "Description",
                schema: "Survey",
                table: "Attribute",
                type: "nvarchar(255)",
                maxLength: 255,
                nullable: false,
                defaultValue: "",
                oldClrType: typeof(string),
                oldType: "nvarchar(1000)",
                oldMaxLength: 1000,
                oldNullable: true);

            migrationBuilder.CreateIndex(
                name: "IX_Attribute_KeyName",
                schema: "Survey",
                table: "Attribute",
                column: "KeyName",
                unique: true);
        }
    }
}
