//<auto-generated/>
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace QuickForm.Modules.Survey.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class AddEntitiesQuestionAttributeValueAndQuestion : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterColumn<Guid>(
                name: "customerId",
                schema: "Survey",
                table: "Forms",
                type: "uniqueidentifier",
                nullable: false,
                defaultValue: new Guid("00000000-0000-0000-0000-000000000000"),
                oldClrType: typeof(Guid),
                oldType: "uniqueidentifier",
                oldNullable: true);

            migrationBuilder.CreateTable(
                name: "Question",
                schema: "Survey",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    IdForm = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    IdQuestionType = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    Order = table.Column<int>(type: "int", nullable: false),
                    CreatedBy = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: false),
                    ModifiedBy = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true),
                    CreatedDate = table.Column<DateTime>(type: "datetime2", nullable: false),
                    ModifiedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    IsActive = table.Column<bool>(type: "bit", nullable: false, defaultValue: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Question", x => x.Id);
                    table.ForeignKey(
                        name: "FK_Question_Forms_IdForm",
                        column: x => x.IdForm,
                        principalSchema: "Survey",
                        principalTable: "Forms",
                        principalColumn: "Id");
                    table.ForeignKey(
                        name: "FK_Question_QuestionType_IdQuestionType",
                        column: x => x.IdQuestionType,
                        principalSchema: "Survey",
                        principalTable: "QuestionType",
                        principalColumn: "Id");
                });

            migrationBuilder.CreateTable(
                name: "QuestionAttributeValue",
                schema: "Survey",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    IdQuestion = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    IdQuestionTypeAttribute = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    Value = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CreatedBy = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: false),
                    ModifiedBy = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true),
                    CreatedDate = table.Column<DateTime>(type: "datetime2", nullable: false),
                    ModifiedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    IsActive = table.Column<bool>(type: "bit", nullable: false, defaultValue: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_QuestionAttributeValue", x => x.Id);
                    table.ForeignKey(
                        name: "FK_QuestionAttributeValue_QuestionTypeAttribute_IdQuestionTypeAttribute",
                        column: x => x.IdQuestionTypeAttribute,
                        principalSchema: "Survey",
                        principalTable: "QuestionTypeAttribute",
                        principalColumn: "Id");
                    table.ForeignKey(
                        name: "FK_QuestionAttributeValue_Question_IdQuestion",
                        column: x => x.IdQuestion,
                        principalSchema: "Survey",
                        principalTable: "Question",
                        principalColumn: "Id");
                });

            migrationBuilder.CreateIndex(
                name: "IX_Question_IdForm",
                schema: "Survey",
                table: "Question",
                column: "IdForm");

            migrationBuilder.CreateIndex(
                name: "IX_Question_IdQuestionType",
                schema: "Survey",
                table: "Question",
                column: "IdQuestionType");

            migrationBuilder.CreateIndex(
                name: "IX_QuestionDomain_IsActive",
                schema: "Survey",
                table: "Question",
                column: "IsActive");

            migrationBuilder.CreateIndex(
                name: "IX_QuestionAttributeValue_IdQuestion",
                schema: "Survey",
                table: "QuestionAttributeValue",
                column: "IdQuestion");

            migrationBuilder.CreateIndex(
                name: "IX_QuestionAttributeValue_IdQuestionTypeAttribute",
                schema: "Survey",
                table: "QuestionAttributeValue",
                column: "IdQuestionTypeAttribute");

            migrationBuilder.CreateIndex(
                name: "IX_QuestionAttributeValueDomain_IsActive",
                schema: "Survey",
                table: "QuestionAttributeValue",
                column: "IsActive");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "QuestionAttributeValue",
                schema: "Survey");

            migrationBuilder.DropTable(
                name: "Question",
                schema: "Survey");

            migrationBuilder.AlterColumn<Guid>(
                name: "customerId",
                schema: "Survey",
                table: "Forms",
                type: "uniqueidentifier",
                nullable: true,
                oldClrType: typeof(Guid),
                oldType: "uniqueidentifier");
        }
    }
}
