//<auto-generated/>
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace QuickForm.Modules.Survey.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class AuditConfiguration : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Forms_Customers_IdCustomer",
                schema: "Survey",
                table: "Forms");

            migrationBuilder.DropPrimaryKey(
                name: "PK_Customers",
                schema: "Survey",
                table: "Customers");

            migrationBuilder.DropPrimaryKey(
                name: "PK_Audit",
                schema: "Survey",
                table: "Audit");

            migrationBuilder.RenameTable(
                name: "Customers",
                schema: "Survey",
                newName: "Customer",
                newSchema: "Survey");

            migrationBuilder.RenameTable(
                name: "Audit",
                schema: "Survey",
                newName: "AuditLog",
                newSchema: "Survey");

            migrationBuilder.AlterColumn<string>(
                name: "UserTransaction",
                schema: "Survey",
                table: "AuditLog",
                type: "nvarchar(200)",
                maxLength: 200,
                nullable: false,
                oldClrType: typeof(string),
                oldType: "nvarchar(max)");

            migrationBuilder.AlterColumn<string>(
                name: "TableName",
                schema: "Survey",
                table: "AuditLog",
                type: "nvarchar(128)",
                maxLength: 128,
                nullable: true,
                oldClrType: typeof(string),
                oldType: "nvarchar(max)",
                oldNullable: true);

            migrationBuilder.AlterColumn<string>(
                name: "ClassOrigin",
                schema: "Survey",
                table: "AuditLog",
                type: "nvarchar(200)",
                maxLength: 200,
                nullable: false,
                oldClrType: typeof(string),
                oldType: "nvarchar(max)");

            migrationBuilder.AlterColumn<string>(
                name: "ActionName",
                schema: "Survey",
                table: "AuditLog",
                type: "nvarchar(64)",
                maxLength: 64,
                nullable: true,
                oldClrType: typeof(string),
                oldType: "nvarchar(max)",
                oldNullable: true);

            migrationBuilder.AlterColumn<string>(
                name: "Action",
                schema: "Survey",
                table: "AuditLog",
                type: "nvarchar(32)",
                maxLength: 32,
                nullable: true,
                oldClrType: typeof(int),
                oldType: "int",
                oldNullable: true);

            migrationBuilder.AddPrimaryKey(
                name: "PK_Customer",
                schema: "Survey",
                table: "Customer",
                column: "Id");

            migrationBuilder.AddPrimaryKey(
                name: "PK_AuditLog",
                schema: "Survey",
                table: "AuditLog",
                column: "Id");

            migrationBuilder.CreateIndex(
                name: "IX_AuditLog_Action",
                schema: "Survey",
                table: "AuditLog",
                column: "Action");

            migrationBuilder.CreateIndex(
                name: "IX_AuditLog_CreatedDate",
                schema: "Survey",
                table: "AuditLog",
                column: "CreatedDate");

            migrationBuilder.CreateIndex(
                name: "IX_AuditLog_Table_Entity_Date",
                schema: "Survey",
                table: "AuditLog",
                columns: new[] { "TableName", "IdEntity" });

            migrationBuilder.CreateIndex(
                name: "IX_AuditLog_TransactionId",
                schema: "Survey",
                table: "AuditLog",
                column: "TransactionId");

            migrationBuilder.AddForeignKey(
                name: "FK_Forms_Customer_IdCustomer",
                schema: "Survey",
                table: "Forms",
                column: "IdCustomer",
                principalSchema: "Survey",
                principalTable: "Customer",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Forms_Customer_IdCustomer",
                schema: "Survey",
                table: "Forms");

            migrationBuilder.DropPrimaryKey(
                name: "PK_Customer",
                schema: "Survey",
                table: "Customer");

            migrationBuilder.DropPrimaryKey(
                name: "PK_AuditLog",
                schema: "Survey",
                table: "AuditLog");

            migrationBuilder.DropIndex(
                name: "IX_AuditLog_Action",
                schema: "Survey",
                table: "AuditLog");

            migrationBuilder.DropIndex(
                name: "IX_AuditLog_CreatedDate",
                schema: "Survey",
                table: "AuditLog");

            migrationBuilder.DropIndex(
                name: "IX_AuditLog_Table_Entity_Date",
                schema: "Survey",
                table: "AuditLog");

            migrationBuilder.DropIndex(
                name: "IX_AuditLog_TransactionId",
                schema: "Survey",
                table: "AuditLog");

            migrationBuilder.RenameTable(
                name: "Customer",
                schema: "Survey",
                newName: "Customers",
                newSchema: "Survey");

            migrationBuilder.RenameTable(
                name: "AuditLog",
                schema: "Survey",
                newName: "Audit",
                newSchema: "Survey");

            migrationBuilder.AlterColumn<string>(
                name: "UserTransaction",
                schema: "Survey",
                table: "Audit",
                type: "nvarchar(max)",
                nullable: false,
                oldClrType: typeof(string),
                oldType: "nvarchar(200)",
                oldMaxLength: 200);

            migrationBuilder.AlterColumn<string>(
                name: "TableName",
                schema: "Survey",
                table: "Audit",
                type: "nvarchar(max)",
                nullable: true,
                oldClrType: typeof(string),
                oldType: "nvarchar(128)",
                oldMaxLength: 128,
                oldNullable: true);

            migrationBuilder.AlterColumn<string>(
                name: "ClassOrigin",
                schema: "Survey",
                table: "Audit",
                type: "nvarchar(max)",
                nullable: false,
                oldClrType: typeof(string),
                oldType: "nvarchar(200)",
                oldMaxLength: 200);

            migrationBuilder.AlterColumn<string>(
                name: "ActionName",
                schema: "Survey",
                table: "Audit",
                type: "nvarchar(max)",
                nullable: true,
                oldClrType: typeof(string),
                oldType: "nvarchar(64)",
                oldMaxLength: 64,
                oldNullable: true);

            migrationBuilder.AlterColumn<int>(
                name: "Action",
                schema: "Survey",
                table: "Audit",
                type: "int",
                nullable: true,
                oldClrType: typeof(string),
                oldType: "nvarchar(32)",
                oldMaxLength: 32,
                oldNullable: true);

            migrationBuilder.AddPrimaryKey(
                name: "PK_Customers",
                schema: "Survey",
                table: "Customers",
                column: "Id");

            migrationBuilder.AddPrimaryKey(
                name: "PK_Audit",
                schema: "Survey",
                table: "Audit",
                column: "Id");

            migrationBuilder.AddForeignKey(
                name: "FK_Forms_Customers_IdCustomer",
                schema: "Survey",
                table: "Forms",
                column: "IdCustomer",
                principalSchema: "Survey",
                principalTable: "Customers",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);
        }
    }
}
