//<auto-generated/>
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace QuickForm.Modules.Survey.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class FormStatusHistory : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "FormStatusHistory",
                schema: "Survey",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    IdForm = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    IdFormStatus = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    CreatedBy = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: false),
                    CreatedDate = table.Column<DateTime>(type: "datetime2", nullable: false),
                    ModifiedBy = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true),
                    ModifiedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    IsDeleted = table.Column<bool>(type: "bit", nullable: false, defaultValue: false),
                    DeletedAt = table.Column<DateTime>(type: "datetime2", nullable: true),
                    DeletedBy = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_FormStatusHistory", x => x.Id);
                    table.ForeignKey(
                        name: "FK_FormStatusHistory_FormStatus_IdFormStatus",
                        column: x => x.IdFormStatus,
                        principalSchema: "Survey",
                        principalTable: "FormStatus",
                        principalColumn: "Id");
                    table.ForeignKey(
                        name: "FK_FormStatusHistory_Forms_IdForm",
                        column: x => x.IdForm,
                        principalSchema: "Survey",
                        principalTable: "Forms",
                        principalColumn: "Id");
                });

            migrationBuilder.CreateIndex(
                name: "IX_FormStatusHistory_IdForm",
                schema: "Survey",
                table: "FormStatusHistory",
                column: "IdForm");

            migrationBuilder.CreateIndex(
                name: "IX_FormStatusHistory_IdFormStatus",
                schema: "Survey",
                table: "FormStatusHistory",
                column: "IdFormStatus");

            migrationBuilder.CreateIndex(
                name: "IX_FormStatusHistoryDomain_IsDeleted",
                schema: "Survey",
                table: "FormStatusHistory",
                column: "IsDeleted");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "FormStatusHistory",
                schema: "Survey");
        }
    }
}
