// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace QuickForm.Modules.Survey.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class FormRender : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterColumn<string>(
                name: "Description",
                schema: "Survey",
                table: "Forms",
                type: "nvarchar(255)",
                maxLength: 255,
                nullable: true,
                oldClrType: typeof(string),
                oldType: "nvarchar(255)",
                oldMaxLength: 255);

            migrationBuilder.CreateTable(
                name: "FormRender",
                schema: "Survey",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    Color = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    Icon = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true),
                    CreatedBy = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: false),
                    CreatedDate = table.Column<DateTime>(type: "datetime2", nullable: false),
                    ModifiedBy = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true),
                    ModifiedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    IsDeleted = table.Column<bool>(type: "bit", nullable: false, defaultValue: false),
                    DeletedAt = table.Column<DateTime>(type: "datetime2", nullable: true),
                    DeletedBy = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true),
                    KeyName = table.Column<string>(type: "nvarchar(200)", maxLength: 200, nullable: false),
                    Description = table.Column<string>(type: "nvarchar(1000)", maxLength: 1000, nullable: true),
                    SortOrder = table.Column<int>(type: "int", nullable: false, defaultValue: 0)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_FormRender", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "FormConfig",
                schema: "Survey",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    FormId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    FormRenderId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    FormRenderDomainId = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    CreatedBy = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: false),
                    CreatedDate = table.Column<DateTime>(type: "datetime2", nullable: false),
                    ModifiedBy = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true),
                    ModifiedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    IsDeleted = table.Column<bool>(type: "bit", nullable: false, defaultValue: false),
                    DeletedAt = table.Column<DateTime>(type: "datetime2", nullable: true),
                    DeletedBy = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_FormConfig", x => x.Id);
                    table.ForeignKey(
                        name: "FK_FormConfig_FormRender_FormRenderDomainId",
                        column: x => x.FormRenderDomainId,
                        principalSchema: "Survey",
                        principalTable: "FormRender",
                        principalColumn: "Id");
                    table.ForeignKey(
                        name: "FK_FormConfig_FormRender_FormRenderId",
                        column: x => x.FormRenderId,
                        principalSchema: "Survey",
                        principalTable: "FormRender",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_FormConfig_Forms_FormId",
                        column: x => x.FormId,
                        principalSchema: "Survey",
                        principalTable: "Forms",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_FormConfig_FormId",
                schema: "Survey",
                table: "FormConfig",
                column: "FormId",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_FormConfig_FormRenderDomainId",
                schema: "Survey",
                table: "FormConfig",
                column: "FormRenderDomainId");

            migrationBuilder.CreateIndex(
                name: "IX_FormConfig_FormRenderId",
                schema: "Survey",
                table: "FormConfig",
                column: "FormRenderId");

            migrationBuilder.CreateIndex(
                name: "IX_FormConfigDomain_IsDeleted",
                schema: "Survey",
                table: "FormConfig",
                column: "IsDeleted");

            migrationBuilder.CreateIndex(
                name: "IX_FormRenderDomain_IsDeleted",
                schema: "Survey",
                table: "FormRender",
                column: "IsDeleted");

            migrationBuilder.CreateIndex(
                name: "IX_FormRenderDomain_KeyName",
                schema: "Survey",
                table: "FormRender",
                column: "KeyName");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "FormConfig",
                schema: "Survey");

            migrationBuilder.DropTable(
                name: "FormRender",
                schema: "Survey");

            migrationBuilder.AlterColumn<string>(
                name: "Description",
                schema: "Survey",
                table: "Forms",
                type: "nvarchar(255)",
                maxLength: 255,
                nullable: false,
                defaultValue: "",
                oldClrType: typeof(string),
                oldType: "nvarchar(255)",
                oldMaxLength: 255,
                oldNullable: true);
        }
    }
}
