//<auto-generated/>
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace QuickForm.Modules.Survey.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class DefaultValidationTemplate : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "DefaultValidationMessage",
                schema: "Survey",
                table: "QuestionTypeRule");

            migrationBuilder.AddColumn<string>(
                name: "ValidationMessage_Default",
                schema: "Survey",
                table: "Rule",
                type: "nvarchar(1000)",
                maxLength: 1000,
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<string>(
                name: "ValidationMessage_Placeholder",
                schema: "Survey",
                table: "Rule",
                type: "nvarchar(1000)",
                maxLength: 1000,
                nullable: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "ValidationMessage_Default",
                schema: "Survey",
                table: "Rule");

            migrationBuilder.DropColumn(
                name: "ValidationMessage_Placeholder",
                schema: "Survey",
                table: "Rule");

            migrationBuilder.AddColumn<string>(
                name: "DefaultValidationMessage",
                schema: "Survey",
                table: "QuestionTypeRule",
                type: "nvarchar(max)",
                nullable: false,
                defaultValue: "");
        }
    }
}
