//<auto-generated/>
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace QuickForm.Modules.Survey.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class SubmissionValueAllValues : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "IX_SubmissionValue_IdQuestion",
                schema: "Survey",
                table: "SubmissionValue");

            migrationBuilder.RenameColumn(
                name: "Value",
                schema: "Survey",
                table: "SubmissionValue",
                newName: "ValueRaw");

            migrationBuilder.AddColumn<string>(
                name: "DisplayValue",
                schema: "Survey",
                table: "SubmissionValue",
                type: "nvarchar(max)",
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<bool>(
                name: "ValueBoolean",
                schema: "Survey",
                table: "SubmissionValue",
                type: "bit",
                nullable: true);

            migrationBuilder.AddColumn<DateTime>(
                name: "ValueDateTime",
                schema: "Survey",
                table: "SubmissionValue",
                type: "datetime2",
                nullable: true);

            migrationBuilder.AddColumn<decimal>(
                name: "ValueDecimal",
                schema: "Survey",
                table: "SubmissionValue",
                type: "decimal(38,10)",
                nullable: true);

            migrationBuilder.AddColumn<long>(
                name: "ValueInteger",
                schema: "Survey",
                table: "SubmissionValue",
                type: "bigint",
                nullable: true);

            migrationBuilder.CreateIndex(
                name: "IX_SubmissionValue_IdQuestion_ValueBoolean",
                schema: "Survey",
                table: "SubmissionValue",
                columns: new[] { "IdQuestion", "ValueBoolean" });

            migrationBuilder.CreateIndex(
                name: "IX_SubmissionValue_IdQuestion_ValueDateTime",
                schema: "Survey",
                table: "SubmissionValue",
                columns: new[] { "IdQuestion", "ValueDateTime" });

            migrationBuilder.CreateIndex(
                name: "IX_SubmissionValue_IdQuestion_ValueDecimal",
                schema: "Survey",
                table: "SubmissionValue",
                columns: new[] { "IdQuestion", "ValueDecimal" });

            migrationBuilder.CreateIndex(
                name: "IX_SubmissionValue_IdQuestion_ValueInteger",
                schema: "Survey",
                table: "SubmissionValue",
                columns: new[] { "IdQuestion", "ValueInteger" });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "IX_SubmissionValue_IdQuestion_ValueBoolean",
                schema: "Survey",
                table: "SubmissionValue");

            migrationBuilder.DropIndex(
                name: "IX_SubmissionValue_IdQuestion_ValueDateTime",
                schema: "Survey",
                table: "SubmissionValue");

            migrationBuilder.DropIndex(
                name: "IX_SubmissionValue_IdQuestion_ValueDecimal",
                schema: "Survey",
                table: "SubmissionValue");

            migrationBuilder.DropIndex(
                name: "IX_SubmissionValue_IdQuestion_ValueInteger",
                schema: "Survey",
                table: "SubmissionValue");

            migrationBuilder.DropColumn(
                name: "DisplayValue",
                schema: "Survey",
                table: "SubmissionValue");

            migrationBuilder.DropColumn(
                name: "ValueBoolean",
                schema: "Survey",
                table: "SubmissionValue");

            migrationBuilder.DropColumn(
                name: "ValueDateTime",
                schema: "Survey",
                table: "SubmissionValue");

            migrationBuilder.DropColumn(
                name: "ValueDecimal",
                schema: "Survey",
                table: "SubmissionValue");

            migrationBuilder.DropColumn(
                name: "ValueInteger",
                schema: "Survey",
                table: "SubmissionValue");

            migrationBuilder.RenameColumn(
                name: "ValueRaw",
                schema: "Survey",
                table: "SubmissionValue",
                newName: "Value");

            migrationBuilder.CreateIndex(
                name: "IX_SubmissionValue_IdQuestion",
                schema: "Survey",
                table: "SubmissionValue",
                column: "IdQuestion");
        }
    }
}
