// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace QuickForm.Modules.Survey.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class Submission : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "Description",
                schema: "Survey",
                table: "QuestionType",
                type: "nvarchar(1000)",
                maxLength: 1000,
                nullable: true);

            migrationBuilder.AddColumn<Guid>(
                name: "IdDataType",
                schema: "Survey",
                table: "QuestionType",
                type: "uniqueidentifier",
                nullable: false,
                defaultValue: new Guid("00000000-0000-0000-0000-000000000000"));

            migrationBuilder.CreateTable(
                name: "Submission",
                schema: "Survey",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    IdForm = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    SubmittedAtUtc = table.Column<DateTime>(type: "datetime2", nullable: false),
                    CreatedBy = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: false),
                    CreatedDate = table.Column<DateTime>(type: "datetime2", nullable: false),
                    ModifiedBy = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true),
                    ModifiedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    IsDeleted = table.Column<bool>(type: "bit", nullable: false, defaultValue: false),
                    DeletedAt = table.Column<DateTime>(type: "datetime2", nullable: true),
                    DeletedBy = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Submission", x => x.Id);
                    table.ForeignKey(
                        name: "FK_Submission_Forms_IdForm",
                        column: x => x.IdForm,
                        principalSchema: "Survey",
                        principalTable: "Forms",
                        principalColumn: "Id");
                });

            migrationBuilder.CreateTable(
                name: "SubmissionValue",
                schema: "Survey",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    IdSubmission = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    IdQuestion = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    Value = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    CreatedBy = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: false),
                    CreatedDate = table.Column<DateTime>(type: "datetime2", nullable: false),
                    ModifiedBy = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true),
                    ModifiedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    IsDeleted = table.Column<bool>(type: "bit", nullable: false, defaultValue: false),
                    DeletedAt = table.Column<DateTime>(type: "datetime2", nullable: true),
                    DeletedBy = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_SubmissionValue", x => x.Id);
                    table.ForeignKey(
                        name: "FK_SubmissionValue_Question_IdQuestion",
                        column: x => x.IdQuestion,
                        principalSchema: "Survey",
                        principalTable: "Question",
                        principalColumn: "Id");
                    table.ForeignKey(
                        name: "FK_SubmissionValue_Submission_IdSubmission",
                        column: x => x.IdSubmission,
                        principalSchema: "Survey",
                        principalTable: "Submission",
                        principalColumn: "Id");
                });

            migrationBuilder.CreateIndex(
                name: "IX_QuestionType_IdDataType",
                schema: "Survey",
                table: "QuestionType",
                column: "IdDataType");

            migrationBuilder.CreateIndex(
                name: "IX_Submission_IdForm",
                schema: "Survey",
                table: "Submission",
                column: "IdForm");

            migrationBuilder.CreateIndex(
                name: "IX_SubmissionDomain_IsDeleted",
                schema: "Survey",
                table: "Submission",
                column: "IsDeleted");

            migrationBuilder.CreateIndex(
                name: "IX_SubmissionValue_IdQuestion",
                schema: "Survey",
                table: "SubmissionValue",
                column: "IdQuestion");

            migrationBuilder.CreateIndex(
                name: "IX_SubmissionValue_IdSubmission",
                schema: "Survey",
                table: "SubmissionValue",
                column: "IdSubmission");

            migrationBuilder.CreateIndex(
                name: "IX_SubmissionValueDomain_IsDeleted",
                schema: "Survey",
                table: "SubmissionValue",
                column: "IsDeleted");

            migrationBuilder.AddForeignKey(
                name: "FK_QuestionType_DataType_IdDataType",
                schema: "Survey",
                table: "QuestionType",
                column: "IdDataType",
                principalSchema: "Survey",
                principalTable: "DataType",
                principalColumn: "Id");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_QuestionType_DataType_IdDataType",
                schema: "Survey",
                table: "QuestionType");

            migrationBuilder.DropTable(
                name: "SubmissionValue",
                schema: "Survey");

            migrationBuilder.DropTable(
                name: "Submission",
                schema: "Survey");

            migrationBuilder.DropIndex(
                name: "IX_QuestionType_IdDataType",
                schema: "Survey",
                table: "QuestionType");

            migrationBuilder.DropColumn(
                name: "Description",
                schema: "Survey",
                table: "QuestionType");

            migrationBuilder.DropColumn(
                name: "IdDataType",
                schema: "Survey",
                table: "QuestionType");
        }
    }
}
