//<auto-generated/>
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace QuickForm.Modules.Survey.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class FilterSchema : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "ConditionalOperator",
                schema: "Survey",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    CreatedBy = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: false),
                    CreatedDate = table.Column<DateTime>(type: "datetime2", nullable: false),
                    ModifiedBy = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true),
                    ModifiedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    IsDeleted = table.Column<bool>(type: "bit", nullable: false, defaultValue: false),
                    DeletedAt = table.Column<DateTime>(type: "datetime2", nullable: true),
                    DeletedBy = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true),
                    KeyName = table.Column<string>(type: "nvarchar(200)", maxLength: 200, nullable: false),
                    Description = table.Column<string>(type: "nvarchar(1000)", maxLength: 1000, nullable: true),
                    SortOrder = table.Column<int>(type: "int", nullable: false, defaultValue: 0)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_ConditionalOperator", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "UiControlType",
                schema: "Survey",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    CreatedBy = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: false),
                    CreatedDate = table.Column<DateTime>(type: "datetime2", nullable: false),
                    ModifiedBy = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true),
                    ModifiedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    IsDeleted = table.Column<bool>(type: "bit", nullable: false, defaultValue: false),
                    DeletedAt = table.Column<DateTime>(type: "datetime2", nullable: true),
                    DeletedBy = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true),
                    KeyName = table.Column<string>(type: "nvarchar(200)", maxLength: 200, nullable: false),
                    Description = table.Column<string>(type: "nvarchar(1000)", maxLength: 1000, nullable: true),
                    SortOrder = table.Column<int>(type: "int", nullable: false, defaultValue: 0)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_UiControlType", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "QuestionTypeFilter",
                schema: "Survey",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    IdConditionalOperator = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    IdUiControlType = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    IdQuestionType = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    CreatedBy = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: false),
                    CreatedDate = table.Column<DateTime>(type: "datetime2", nullable: false),
                    ModifiedBy = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true),
                    ModifiedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    IsDeleted = table.Column<bool>(type: "bit", nullable: false, defaultValue: false),
                    DeletedAt = table.Column<DateTime>(type: "datetime2", nullable: true),
                    DeletedBy = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_QuestionTypeFilter", x => x.Id);
                    table.ForeignKey(
                        name: "FK_QuestionTypeFilter_ConditionalOperator_IdConditionalOperator",
                        column: x => x.IdConditionalOperator,
                        principalSchema: "Survey",
                        principalTable: "ConditionalOperator",
                        principalColumn: "Id");
                    table.ForeignKey(
                        name: "FK_QuestionTypeFilter_QuestionType_IdQuestionType",
                        column: x => x.IdQuestionType,
                        principalSchema: "Survey",
                        principalTable: "QuestionType",
                        principalColumn: "Id");
                    table.ForeignKey(
                        name: "FK_QuestionTypeFilter_UiControlType_IdUiControlType",
                        column: x => x.IdUiControlType,
                        principalSchema: "Survey",
                        principalTable: "UiControlType",
                        principalColumn: "Id");
                });

            migrationBuilder.CreateIndex(
                name: "IX_ConditionalOperatorDomain_IsDeleted",
                schema: "Survey",
                table: "ConditionalOperator",
                column: "IsDeleted");

            migrationBuilder.CreateIndex(
                name: "IX_ConditionalOperatorDomain_KeyName",
                schema: "Survey",
                table: "ConditionalOperator",
                column: "KeyName");

            migrationBuilder.CreateIndex(
                name: "IX_QuestionTypeFilter_IdConditionalOperator",
                schema: "Survey",
                table: "QuestionTypeFilter",
                column: "IdConditionalOperator");

            migrationBuilder.CreateIndex(
                name: "IX_QuestionTypeFilter_IdQuestionType",
                schema: "Survey",
                table: "QuestionTypeFilter",
                column: "IdQuestionType");

            migrationBuilder.CreateIndex(
                name: "IX_QuestionTypeFilter_IdUiControlType",
                schema: "Survey",
                table: "QuestionTypeFilter",
                column: "IdUiControlType");

            migrationBuilder.CreateIndex(
                name: "IX_QuestionTypeFilterDomain_IsDeleted",
                schema: "Survey",
                table: "QuestionTypeFilter",
                column: "IsDeleted");

            migrationBuilder.CreateIndex(
                name: "IX_UiControlTypeDomain_IsDeleted",
                schema: "Survey",
                table: "UiControlType",
                column: "IsDeleted");

            migrationBuilder.CreateIndex(
                name: "IX_UiControlTypeDomain_KeyName",
                schema: "Survey",
                table: "UiControlType",
                column: "KeyName");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "QuestionTypeFilter",
                schema: "Survey");

            migrationBuilder.DropTable(
                name: "ConditionalOperator",
                schema: "Survey");

            migrationBuilder.DropTable(
                name: "UiControlType",
                schema: "Survey");
        }
    }
}
