//<auto-generated/>

using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace QuickForm.Modules.Survey.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class RuleWithMessage : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "DefaultValidationMessage",
                schema: "Survey",
                table: "QuestionTypeRule",
                type: "nvarchar(max)",
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<string>(
                name: "Message",
                schema: "Survey",
                table: "QuestionRuleValue",
                type: "nvarchar(max)",
                nullable: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "DefaultValidationMessage",
                schema: "Survey",
                table: "QuestionTypeRule");

            migrationBuilder.DropColumn(
                name: "Message",
                schema: "Survey",
                table: "QuestionRuleValue");
        }
    }
}
