//<auto-generated/>
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace QuickForm.Modules.Users.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class AuditConfiguration : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropPrimaryKey(
                name: "PK_Audit",
                schema: "Auth",
                table: "Audit");

            migrationBuilder.DropColumn(
                name: "LastName",
                schema: "Auth",
                table: "Users");

            migrationBuilder.DropColumn(
                name: "Name",
                schema: "Auth",
                table: "Users");

            migrationBuilder.RenameTable(
                name: "Audit",
                schema: "Auth",
                newName: "AuditLog",
                newSchema: "Auth");

            migrationBuilder.AlterColumn<string>(
                name: "UserTransaction",
                schema: "Auth",
                table: "AuditLog",
                type: "nvarchar(200)",
                maxLength: 200,
                nullable: false,
                oldClrType: typeof(string),
                oldType: "nvarchar(max)");

            migrationBuilder.AlterColumn<string>(
                name: "TableName",
                schema: "Auth",
                table: "AuditLog",
                type: "nvarchar(128)",
                maxLength: 128,
                nullable: true,
                oldClrType: typeof(string),
                oldType: "nvarchar(max)",
                oldNullable: true);

            migrationBuilder.AlterColumn<string>(
                name: "ClassOrigin",
                schema: "Auth",
                table: "AuditLog",
                type: "nvarchar(200)",
                maxLength: 200,
                nullable: false,
                oldClrType: typeof(string),
                oldType: "nvarchar(max)");

            migrationBuilder.AlterColumn<string>(
                name: "ActionName",
                schema: "Auth",
                table: "AuditLog",
                type: "nvarchar(64)",
                maxLength: 64,
                nullable: true,
                oldClrType: typeof(string),
                oldType: "nvarchar(max)",
                oldNullable: true);

            migrationBuilder.AlterColumn<string>(
                name: "Action",
                schema: "Auth",
                table: "AuditLog",
                type: "nvarchar(32)",
                maxLength: 32,
                nullable: true,
                oldClrType: typeof(int),
                oldType: "int",
                oldNullable: true);

            migrationBuilder.AddPrimaryKey(
                name: "PK_AuditLog",
                schema: "Auth",
                table: "AuditLog",
                column: "Id");

            migrationBuilder.CreateIndex(
                name: "IX_AuditLog_Action",
                schema: "Auth",
                table: "AuditLog",
                column: "Action");

            migrationBuilder.CreateIndex(
                name: "IX_AuditLog_CreatedDate",
                schema: "Auth",
                table: "AuditLog",
                column: "CreatedDate");

            migrationBuilder.CreateIndex(
                name: "IX_AuditLog_Table_Entity_Date",
                schema: "Auth",
                table: "AuditLog",
                columns: new[] { "TableName", "IdEntity" });

            migrationBuilder.CreateIndex(
                name: "IX_AuditLog_TransactionId",
                schema: "Auth",
                table: "AuditLog",
                column: "TransactionId");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropPrimaryKey(
                name: "PK_AuditLog",
                schema: "Auth",
                table: "AuditLog");

            migrationBuilder.DropIndex(
                name: "IX_AuditLog_Action",
                schema: "Auth",
                table: "AuditLog");

            migrationBuilder.DropIndex(
                name: "IX_AuditLog_CreatedDate",
                schema: "Auth",
                table: "AuditLog");

            migrationBuilder.DropIndex(
                name: "IX_AuditLog_Table_Entity_Date",
                schema: "Auth",
                table: "AuditLog");

            migrationBuilder.DropIndex(
                name: "IX_AuditLog_TransactionId",
                schema: "Auth",
                table: "AuditLog");

            migrationBuilder.RenameTable(
                name: "AuditLog",
                schema: "Auth",
                newName: "Audit",
                newSchema: "Auth");

            migrationBuilder.AddColumn<string>(
                name: "LastName",
                schema: "Auth",
                table: "Users",
                type: "nvarchar(max)",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "Name",
                schema: "Auth",
                table: "Users",
                type: "nvarchar(max)",
                nullable: false,
                defaultValue: "");

            migrationBuilder.AlterColumn<string>(
                name: "UserTransaction",
                schema: "Auth",
                table: "Audit",
                type: "nvarchar(max)",
                nullable: false,
                oldClrType: typeof(string),
                oldType: "nvarchar(200)",
                oldMaxLength: 200);

            migrationBuilder.AlterColumn<string>(
                name: "TableName",
                schema: "Auth",
                table: "Audit",
                type: "nvarchar(max)",
                nullable: true,
                oldClrType: typeof(string),
                oldType: "nvarchar(128)",
                oldMaxLength: 128,
                oldNullable: true);

            migrationBuilder.AlterColumn<string>(
                name: "ClassOrigin",
                schema: "Auth",
                table: "Audit",
                type: "nvarchar(max)",
                nullable: false,
                oldClrType: typeof(string),
                oldType: "nvarchar(200)",
                oldMaxLength: 200);

            migrationBuilder.AlterColumn<string>(
                name: "ActionName",
                schema: "Auth",
                table: "Audit",
                type: "nvarchar(max)",
                nullable: true,
                oldClrType: typeof(string),
                oldType: "nvarchar(64)",
                oldMaxLength: 64,
                oldNullable: true);

            migrationBuilder.AlterColumn<int>(
                name: "Action",
                schema: "Auth",
                table: "Audit",
                type: "int",
                nullable: true,
                oldClrType: typeof(string),
                oldType: "nvarchar(32)",
                oldMaxLength: 32,
                oldNullable: true);

            migrationBuilder.AddPrimaryKey(
                name: "PK_Audit",
                schema: "Auth",
                table: "Audit",
                column: "Id");
        }
    }
}
