//<auto-generated/>
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace QuickForm.Modules.Users.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class ChangeAuthActionAndRoleWithMaster : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterColumn<string>(
                name: "Description",
                schema: "Auth",
                table: "Role",
                type: "nvarchar(max)",
                nullable: true,
                oldClrType: typeof(string),
                oldType: "nvarchar(255)",
                oldMaxLength: 255);

            migrationBuilder.AddColumn<string>(
                name: "KeyName",
                schema: "Auth",
                table: "Role",
                type: "nvarchar(200)",
                maxLength: 200,
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<int>(
                name: "SortOrder",
                schema: "Auth",
                table: "Role",
                type: "int",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AlterColumn<string>(
                name: "Description",
                schema: "Auth",
                table: "AuthActions",
                type: "nvarchar(max)",
                nullable: true,
                oldClrType: typeof(string),
                oldType: "nvarchar(255)",
                oldMaxLength: 255);

            migrationBuilder.AddColumn<string>(
                name: "KeyName",
                schema: "Auth",
                table: "AuthActions",
                type: "nvarchar(200)",
                maxLength: 200,
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<int>(
                name: "SortOrder",
                schema: "Auth",
                table: "AuthActions",
                type: "int",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.CreateIndex(
                name: "UX_RoleDomain_KeyName",
                schema: "Auth",
                table: "Role",
                column: "KeyName");

            migrationBuilder.CreateIndex(
                name: "UX_AuthActionDomain_KeyName",
                schema: "Auth",
                table: "AuthActions",
                column: "KeyName");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "UX_RoleDomain_KeyName",
                schema: "Auth",
                table: "Role");

            migrationBuilder.DropIndex(
                name: "UX_AuthActionDomain_KeyName",
                schema: "Auth",
                table: "AuthActions");

            migrationBuilder.DropColumn(
                name: "KeyName",
                schema: "Auth",
                table: "Role");

            migrationBuilder.DropColumn(
                name: "SortOrder",
                schema: "Auth",
                table: "Role");

            migrationBuilder.DropColumn(
                name: "KeyName",
                schema: "Auth",
                table: "AuthActions");

            migrationBuilder.DropColumn(
                name: "SortOrder",
                schema: "Auth",
                table: "AuthActions");

            migrationBuilder.AlterColumn<string>(
                name: "Description",
                schema: "Auth",
                table: "Role",
                type: "nvarchar(255)",
                maxLength: 255,
                nullable: false,
                defaultValue: "",
                oldClrType: typeof(string),
                oldType: "nvarchar(max)",
                oldNullable: true);

            migrationBuilder.AlterColumn<string>(
                name: "Description",
                schema: "Auth",
                table: "AuthActions",
                type: "nvarchar(255)",
                maxLength: 255,
                nullable: false,
                defaultValue: "",
                oldClrType: typeof(string),
                oldType: "nvarchar(max)",
                oldNullable: true);
        }
    }
}
