//<auto-generated/>

using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace QuickForm.Modules.Users.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class ChangeActionAndResourcePermissionWithMaster : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterColumn<string>(
                name: "Description",
                schema: "Auth",
                table: "Resources",
                type: "nvarchar(max)",
                nullable: true,
                oldClrType: typeof(string),
                oldType: "nvarchar(255)",
                oldMaxLength: 255);

            migrationBuilder.AddColumn<string>(
                name: "KeyName",
                schema: "Auth",
                table: "Resources",
                type: "nvarchar(200)",
                maxLength: 200,
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<int>(
                name: "SortOrder",
                schema: "Auth",
                table: "Resources",
                type: "int",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AlterColumn<string>(
                name: "Description",
                schema: "Auth",
                table: "PermissionsActions",
                type: "nvarchar(max)",
                nullable: true,
                oldClrType: typeof(string),
                oldType: "nvarchar(255)",
                oldMaxLength: 255);

            migrationBuilder.AddColumn<string>(
                name: "KeyName",
                schema: "Auth",
                table: "PermissionsActions",
                type: "nvarchar(200)",
                maxLength: 200,
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<int>(
                name: "SortOrder",
                schema: "Auth",
                table: "PermissionsActions",
                type: "int",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.CreateIndex(
                name: "UX_ResourcesDomain_KeyName",
                schema: "Auth",
                table: "Resources",
                column: "KeyName");

            migrationBuilder.CreateIndex(
                name: "UX_PermissionsActionsDomain_KeyName",
                schema: "Auth",
                table: "PermissionsActions",
                column: "KeyName");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "UX_ResourcesDomain_KeyName",
                schema: "Auth",
                table: "Resources");

            migrationBuilder.DropIndex(
                name: "UX_PermissionsActionsDomain_KeyName",
                schema: "Auth",
                table: "PermissionsActions");

            migrationBuilder.DropColumn(
                name: "KeyName",
                schema: "Auth",
                table: "Resources");

            migrationBuilder.DropColumn(
                name: "SortOrder",
                schema: "Auth",
                table: "Resources");

            migrationBuilder.DropColumn(
                name: "KeyName",
                schema: "Auth",
                table: "PermissionsActions");

            migrationBuilder.DropColumn(
                name: "SortOrder",
                schema: "Auth",
                table: "PermissionsActions");

            migrationBuilder.AlterColumn<string>(
                name: "Description",
                schema: "Auth",
                table: "Resources",
                type: "nvarchar(255)",
                maxLength: 255,
                nullable: false,
                defaultValue: "",
                oldClrType: typeof(string),
                oldType: "nvarchar(max)",
                oldNullable: true);

            migrationBuilder.AlterColumn<string>(
                name: "Description",
                schema: "Auth",
                table: "PermissionsActions",
                type: "nvarchar(255)",
                maxLength: 255,
                nullable: false,
                defaultValue: "",
                oldClrType: typeof(string),
                oldType: "nvarchar(max)",
                oldNullable: true);
        }
    }
}
