//<auto-generated/>
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace QuickForm.Modules.Users.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class ChangePermissionTable : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "HttpMethod",
                schema: "Auth",
                table: "Permissions",
                type: "nvarchar(200)",
                maxLength: 200,
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<Guid>(
                name: "IdApplication",
                schema: "Auth",
                table: "Permissions",
                type: "uniqueidentifier",
                nullable: false,
                defaultValue: new Guid("00000000-0000-0000-0000-000000000000"));

            migrationBuilder.AddColumn<string>(
                name: "KeyName",
                schema: "Auth",
                table: "Permissions",
                type: "nvarchar(200)",
                maxLength: 200,
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<string>(
                name: "PathUrl",
                schema: "Auth",
                table: "Permissions",
                type: "nvarchar(200)",
                maxLength: 200,
                nullable: false,
                defaultValue: "");

            migrationBuilder.CreateTable(
                name: "Application",
                schema: "Auth",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    CreatedBy = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: false),
                    ModifiedBy = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true),
                    CreatedDate = table.Column<DateTime>(type: "datetime2", nullable: false),
                    ModifiedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    IsDeleted = table.Column<bool>(type: "bit", nullable: false, defaultValue: false),
                    DeletedAt = table.Column<DateTime>(type: "datetime2", nullable: true),
                    DeletedBy = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true),
                    KeyName = table.Column<string>(type: "nvarchar(200)", maxLength: 200, nullable: false),
                    Description = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SortOrder = table.Column<int>(type: "int", nullable: false, defaultValue: 0)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Application", x => x.Id);
                });

            migrationBuilder.CreateIndex(
                name: "IX_Permissions_IdApplication",
                schema: "Auth",
                table: "Permissions",
                column: "IdApplication");

            migrationBuilder.CreateIndex(
                name: "IX_ApplicationDomain_IsDeleted",
                schema: "Auth",
                table: "Application",
                column: "IsDeleted");

            migrationBuilder.CreateIndex(
                name: "UX_ApplicationDomain_KeyName",
                schema: "Auth",
                table: "Application",
                column: "KeyName");

            migrationBuilder.AddForeignKey(
                name: "FK_Permissions_Application_IdApplication",
                schema: "Auth",
                table: "Permissions",
                column: "IdApplication",
                principalSchema: "Auth",
                principalTable: "Application",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Permissions_Application_IdApplication",
                schema: "Auth",
                table: "Permissions");

            migrationBuilder.DropTable(
                name: "Application",
                schema: "Auth");

            migrationBuilder.DropIndex(
                name: "IX_Permissions_IdApplication",
                schema: "Auth",
                table: "Permissions");

            migrationBuilder.DropColumn(
                name: "HttpMethod",
                schema: "Auth",
                table: "Permissions");

            migrationBuilder.DropColumn(
                name: "IdApplication",
                schema: "Auth",
                table: "Permissions");

            migrationBuilder.DropColumn(
                name: "KeyName",
                schema: "Auth",
                table: "Permissions");

            migrationBuilder.DropColumn(
                name: "PathUrl",
                schema: "Auth",
                table: "Permissions");
        }
    }
}
