//<auto-generated/>
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace QuickForm.Modules.Users.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class ChangeNameIdDomainEventToIdOutboxMessage : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.RenameColumn(
                name: "IdDomainEvent",
                schema: "Auth",
                table: "inbox_messages",
                newName: "IdOutboxMessage");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.RenameColumn(
                name: "IdOutboxMessage",
                schema: "Auth",
                table: "inbox_messages",
                newName: "IdDomainEvent");
        }
    }
}
