// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace QuickForm.Modules.Users.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class ImproveSecurityOfToken : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "IX_UserRole_IdUser",
                schema: "Auth",
                table: "UserRole");

            migrationBuilder.DropIndex(
                name: "IX_RolePermissions_IdPermission",
                schema: "Auth",
                table: "RolePermissions");

            migrationBuilder.DropIndex(
                name: "IX_AuthActionTokens_IdUser",
                schema: "Auth",
                table: "AuthActionTokens");

            migrationBuilder.DropIndex(
                name: "IX_AuthActionTokens_IdUserAction",
                schema: "Auth",
                table: "AuthActionTokens");

            migrationBuilder.DropColumn(
                name: "Token",
                schema: "Auth",
                table: "AuthActionTokens");

            migrationBuilder.RenameIndex(
                name: "UX_RoleDomain_KeyName",
                schema: "Auth",
                table: "Role",
                newName: "IX_RoleDomain_KeyName");

            migrationBuilder.RenameIndex(
                name: "UX_ResourcesDomain_KeyName",
                schema: "Auth",
                table: "Resources",
                newName: "IX_ResourcesDomain_KeyName");

            migrationBuilder.RenameIndex(
                name: "UX_PermissionsActionsDomain_KeyName",
                schema: "Auth",
                table: "PermissionsActions",
                newName: "IX_PermissionsActionsDomain_KeyName");

            migrationBuilder.RenameIndex(
                name: "UX_AuthActionDomain_KeyName",
                schema: "Auth",
                table: "AuthActions",
                newName: "IX_AuthActionDomain_KeyName");

            migrationBuilder.RenameIndex(
                name: "UX_ApplicationDomain_KeyName",
                schema: "Auth",
                table: "Application",
                newName: "IX_ApplicationDomain_KeyName");

            migrationBuilder.AlterColumn<string>(
                name: "Description",
                schema: "Auth",
                table: "Role",
                type: "nvarchar(1000)",
                maxLength: 1000,
                nullable: true,
                oldClrType: typeof(string),
                oldType: "nvarchar(max)",
                oldNullable: true);

            migrationBuilder.AlterColumn<string>(
                name: "Description",
                schema: "Auth",
                table: "Resources",
                type: "nvarchar(1000)",
                maxLength: 1000,
                nullable: true,
                oldClrType: typeof(string),
                oldType: "nvarchar(max)",
                oldNullable: true);

            migrationBuilder.AlterColumn<string>(
                name: "Description",
                schema: "Auth",
                table: "PermissionsActions",
                type: "nvarchar(1000)",
                maxLength: 1000,
                nullable: true,
                oldClrType: typeof(string),
                oldType: "nvarchar(max)",
                oldNullable: true);

            migrationBuilder.AddColumn<string>(
                name: "TokenHash",
                schema: "Auth",
                table: "AuthActionTokens",
                type: "nvarchar(200)",
                maxLength: 200,
                nullable: false,
                defaultValue: "");

            migrationBuilder.AlterColumn<string>(
                name: "Description",
                schema: "Auth",
                table: "AuthActions",
                type: "nvarchar(1000)",
                maxLength: 1000,
                nullable: true,
                oldClrType: typeof(string),
                oldType: "nvarchar(max)",
                oldNullable: true);

            migrationBuilder.AlterColumn<string>(
                name: "Description",
                schema: "Auth",
                table: "Application",
                type: "nvarchar(1000)",
                maxLength: 1000,
                nullable: true,
                oldClrType: typeof(string),
                oldType: "nvarchar(max)",
                oldNullable: true);

            migrationBuilder.CreateIndex(
                name: "IX_Users_Email",
                schema: "Auth",
                table: "Users",
                column: "Email",
                unique: true,
                filter: "[IsDeleted] = 0");

            migrationBuilder.CreateIndex(
                name: "IX_UserRole_IdUser_IdRole",
                schema: "Auth",
                table: "UserRole",
                columns: new[] { "IdUser", "IdRole" },
                unique: true,
                filter: "[IsDeleted] = 0");

            migrationBuilder.CreateIndex(
                name: "IX_RolePermissions_IdPermission_IdRole",
                schema: "Auth",
                table: "RolePermissions",
                columns: new[] { "IdPermission", "IdRole" },
                unique: true,
                filter: "[IsDeleted] = 0");

            migrationBuilder.CreateIndex(
                name: "IX_AuthActionTokens_IdUser_IdUserAction_Used_ExpiresAt",
                schema: "Auth",
                table: "AuthActionTokens",
                columns: new[] { "IdUser", "IdUserAction", "Used", "ExpiresAt" });

            migrationBuilder.CreateIndex(
                name: "IX_AuthActionTokens_IdUserAction_TokenHash",
                schema: "Auth",
                table: "AuthActionTokens",
                columns: new[] { "IdUserAction", "TokenHash" });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "IX_Users_Email",
                schema: "Auth",
                table: "Users");

            migrationBuilder.DropIndex(
                name: "IX_UserRole_IdUser_IdRole",
                schema: "Auth",
                table: "UserRole");

            migrationBuilder.DropIndex(
                name: "IX_RolePermissions_IdPermission_IdRole",
                schema: "Auth",
                table: "RolePermissions");

            migrationBuilder.DropIndex(
                name: "IX_AuthActionTokens_IdUser_IdUserAction_Used_ExpiresAt",
                schema: "Auth",
                table: "AuthActionTokens");

            migrationBuilder.DropIndex(
                name: "IX_AuthActionTokens_IdUserAction_TokenHash",
                schema: "Auth",
                table: "AuthActionTokens");

            migrationBuilder.DropColumn(
                name: "TokenHash",
                schema: "Auth",
                table: "AuthActionTokens");

            migrationBuilder.RenameIndex(
                name: "IX_RoleDomain_KeyName",
                schema: "Auth",
                table: "Role",
                newName: "UX_RoleDomain_KeyName");

            migrationBuilder.RenameIndex(
                name: "IX_ResourcesDomain_KeyName",
                schema: "Auth",
                table: "Resources",
                newName: "UX_ResourcesDomain_KeyName");

            migrationBuilder.RenameIndex(
                name: "IX_PermissionsActionsDomain_KeyName",
                schema: "Auth",
                table: "PermissionsActions",
                newName: "UX_PermissionsActionsDomain_KeyName");

            migrationBuilder.RenameIndex(
                name: "IX_AuthActionDomain_KeyName",
                schema: "Auth",
                table: "AuthActions",
                newName: "UX_AuthActionDomain_KeyName");

            migrationBuilder.RenameIndex(
                name: "IX_ApplicationDomain_KeyName",
                schema: "Auth",
                table: "Application",
                newName: "UX_ApplicationDomain_KeyName");

            migrationBuilder.AlterColumn<string>(
                name: "Description",
                schema: "Auth",
                table: "Role",
                type: "nvarchar(max)",
                nullable: true,
                oldClrType: typeof(string),
                oldType: "nvarchar(1000)",
                oldMaxLength: 1000,
                oldNullable: true);

            migrationBuilder.AlterColumn<string>(
                name: "Description",
                schema: "Auth",
                table: "Resources",
                type: "nvarchar(max)",
                nullable: true,
                oldClrType: typeof(string),
                oldType: "nvarchar(1000)",
                oldMaxLength: 1000,
                oldNullable: true);

            migrationBuilder.AlterColumn<string>(
                name: "Description",
                schema: "Auth",
                table: "PermissionsActions",
                type: "nvarchar(max)",
                nullable: true,
                oldClrType: typeof(string),
                oldType: "nvarchar(1000)",
                oldMaxLength: 1000,
                oldNullable: true);

            migrationBuilder.AddColumn<string>(
                name: "Token",
                schema: "Auth",
                table: "AuthActionTokens",
                type: "nvarchar(255)",
                maxLength: 255,
                nullable: false,
                defaultValue: "");

            migrationBuilder.AlterColumn<string>(
                name: "Description",
                schema: "Auth",
                table: "AuthActions",
                type: "nvarchar(max)",
                nullable: true,
                oldClrType: typeof(string),
                oldType: "nvarchar(1000)",
                oldMaxLength: 1000,
                oldNullable: true);

            migrationBuilder.AlterColumn<string>(
                name: "Description",
                schema: "Auth",
                table: "Application",
                type: "nvarchar(max)",
                nullable: true,
                oldClrType: typeof(string),
                oldType: "nvarchar(1000)",
                oldMaxLength: 1000,
                oldNullable: true);

            migrationBuilder.CreateIndex(
                name: "IX_UserRole_IdUser",
                schema: "Auth",
                table: "UserRole",
                column: "IdUser");

            migrationBuilder.CreateIndex(
                name: "IX_RolePermissions_IdPermission",
                schema: "Auth",
                table: "RolePermissions",
                column: "IdPermission");

            migrationBuilder.CreateIndex(
                name: "IX_AuthActionTokens_IdUser",
                schema: "Auth",
                table: "AuthActionTokens",
                column: "IdUser");

            migrationBuilder.CreateIndex(
                name: "IX_AuthActionTokens_IdUserAction",
                schema: "Auth",
                table: "AuthActionTokens",
                column: "IdUserAction");
        }
    }
}
